apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - ./cluster-issuer.yml
  - ./certificate.yml
patches:
  - target:
      kind: ServiceAccount
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: "/metadata/annotations/iam.gke.io~1gcp-service-account"
        value: gke-clouddns@deploys-dev.iam.gserviceaccount.com
