apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: beta-deploys-dev
spec:
  provider:
    gcpsm:
      projectID: deploys-dev
      auth:
        workloadIdentity:
          clusterLocation: asia-southeast1-a
          clusterName: deploys-dev-production
          serviceAccountRef:
            name: gke-externalsecrets
            namespace: default
