apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api.deploys.dev
  namespace: default
spec:
  secretName: api.deploys.dev
  issuerRef:
    name: google-issuer
    kind: ClusterIssuer
  commonName: 'api.deploys.dev'
  dnsNames:
  - 'api.deploys.dev'
