apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: codedeploy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: beta-deploys-dev
  target:
    name: codedeploy-secret
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: postgres-password
    - secretKey: firebase-service-account-key
      remoteRef:
        key: firebase-service-account-key
