apiVersion: v1
kind: Namespace
metadata:
  name: codedeploy-internal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codedeploy-imagebuilder
  namespace: codedeploy-internal
  annotations:
    iam.gke.io/gcp-service-account: gke-artifactregistry@deploys-dev.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codedeploy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codedeploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codedeploy
subjects:
- kind: ServiceAccount
  name: codedeploy
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codedeploy
  namespace: default
