apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: beta-deploys-dev
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-password
    - secretKey: replicationPassword
      remoteRef:
        key: postgres-replication-password
